### ISSUE TITLE
Regex in URI

### ISSUE THREAD

**Issue by charles-d-burton** [kevholditch/terraform-provider-kong#10]
So, ran into something else.  Curious to know if you think this is something that can be fixed.  I'm trying to add a route that contains a regular expression, but I can't seem to get it to take in terraform.  When I try to run it, kong tries to inject additional escapes.  If I don't add the escapes, terraform blows up with illegal characters:
```hcl
resource "kong_api" "mf-public-web" {
  name = "mf-public-web"

  uris = [
    "\\^\\/certificates\\/\\w+.aspx",
  ]

  methods                  = ["GET", "POST", "UPDATE", "PATCH", "DELETE"]
  upstream_url             = "${lookup(var.mf-public-web, var.env)}"
  strip_uri                = false
  preserve_host            = false
  retries                  = 3
  upstream_connect_timeout = 60000
  upstream_send_timeout    = 30000
  upstream_read_timeout    = 10000
  https_only               = false
  http_if_terminated       = false
}

```

**Comment by kevholditch** [comment]
Can you get this working with curl/postman if you post directly to kong without terraform?  That's the first thing I would try to work out how you need to escape the regex.  Once you have that working you can work up the stack by trying it in the [gokong](github.com/kevholditch/gokong) library by writing a simple test with your regex from how you curled it and see if it creates the API.  Once that works move up to terraform and you could write a test for this case in the `kong_api_resource`
