### ISSUE TITLE
Publish to Terraform registry

### ISSUE THREAD

**Issue by jgillich** [kevholditch/terraform-provider-kong#106]
Hi @kevholditch,

It would be awesome if you could publish this module to the [Terraform registry](https://registry.terraform.io/). It would make it installable via a simple `terraform init` and also make it useable on Terraform Cloud.

Thanks!

**Comment by hbagdi** [comment]
Thanks for opening this issue. This is something I'm interested in doing but is not the highest priority right now.
(@judithpatudith, hello again)

**Comment by judithpatudith** [comment]
Hi again 👋

**Comment by loafoe** [comment]
Hi, I've created a PR #117 which updates the goreleaser config to create releases suitable for publishing on the registry

**Comment by kevholditch** [comment]
This provider has been updated and published to the registry
