### ISSUE TITLE
Latest stable release for Kong 1.5

### ISSUE THREAD

**Issue by jassmakhija** [kevholditch/terraform-provider-kong#111]
Hi,

I have recently upgraded to Kong 1.5, but I am not able figure out, which version of "terraform-provider-kong" should be used. As per the "latest" release, it is v1.12.0 but I see other higher version as well like v5.2.1.

Looking forward for your help :) 👍 

Thanks
Jas

**Comment by kevholditch** [comment]
Hey, the latest version of the provider `v6.1.3` supports `v2.X` of Kong
