### ISSUE TITLE
Is this project being maintained?

### ISSUE THREAD

**Issue by janders223** [kevholditch/terraform-provider-kong#113]
Looking at the commit activity and pull requests like #106 that has been open for months and #110 that hasn't even received a comment from the maintainers to acknowledge it's presence makes me think this project is dying.

Terraform 0.13 is out and makes it harder to use providers that are not on the registry in CI/CD without tons of setup which means that #106 can no longer be ignored. 

I 100% understand the struggle of maintaining an open-source project and appreciate all of the hard work that has gone into this project. However, I rely on this every single day and it would be nice to know that it will be supported moving forward or if another direction is needed.

Thanks!

**Comment by wkokolis** [comment]
@janders223 I think, unfortunately, that this project is dead.  If you haven't seen it yet, Philips-Labs has forked the project and is continuing it: https://registry.terraform.io/providers/philips-labs/kong/latest / https://github.com/philips-labs/terraform-provider-kong.  Their newest release is March 14th, 2021.

**Comment by kevholditch** [comment]
unfortunately this project was dead for a while as I had a 2nd child and couldn't find time to work on it.  I've now got a bit more time so am going to try and get the provider up and running agagin.  Have just finished moving to using the official [kong client](https://github.com/Kong/go-kong) from here I'm planning on adding to the official registry.  I may need help to keep the momentum going so if people are willing to volunteer time then that would be amazing.
