### ISSUE TITLE
Feature: BasicAuth for AdminApi

### ISSUE THREAD

**Issue by jochen42** [kevholditch/terraform-provider-kong#12]
Hi!

we are using kong with the kong-loopback-admin api according the following article:
https://getkong.org/docs/0.11.x/secure-admin-api/

Now we wan't to manage kong api's with terraform. To be able to do this, we need to support basic-auth for the admin-api requests.

I already created an pull-request in the dependency [gokong](https://github.com/kevholditch/gokong/pull/9).
In some minutes i will create an pull-request here. But i guess the Tests will fail until the gokong-pr is merged. 

have a nice weekend, jochen

**Comment by kevholditch** [comment]
Thanks for your contribution it is much appreciated

**Comment by jochen42** [comment]
it was a pleasure for me! thanks for the great plugin!
