### ISSUE TITLE
Missing fields on some resources

### ISSUE THREAD

**Issue by kevholditch** [kevholditch/terraform-provider-kong#125]
- service missing fields
  - [x] tags
  - [x] client_certificate
  - [x] tls_verify
  - [x] tls_verify_depth
  - [x] ca_certificates

- route missing fields
  - [x] headers
  - [x] https_redirect_status_code
  - [x] path_handling
  - [x] request_buffering
  - [x] response_buffering
  - [x] tags

- upstream missing fields
  - [x] host_header
  - [x] client_certificate
  - [x] tags

**Comment by hbagdi** [comment]
FYI, Tags are present on every resource in Kong now.

**Comment by kevholditch** [comment]
@hbagdi thanks for the heads up
