### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by dmportella** [kevholditch/terraform-provider-kong#19]
Just letting you know thx for putting the terraform provider together it works like a treat 

currently using it for work all is well.

**Comment by kevholditch** [comment]
@dmportella Thanks! Much appreciated.  There are a few things that need tweaking to improve things but glad you are getting use out of it.

**Comment by kevholditch** [comment]
@dmportella that's a neat idea.  I don't think it would be too complex to do.  Make a nice little open source project
