### ISSUE TITLE
Provider URL problem

### ISSUE THREAD

**Issue by mindflash-ops** [kevholditch/terraform-provider-kong#23]
I'm wondering if anyone has ideas on this.  I'm trying to use configure the provider block to use a secure endpoint secured with an API token.  If I run curl against this endpoint using the same values it works, but the when configured in the provider it does not work.

```hcl
provider "kong" {
  kong_admin_uri = "https://${var.kong_url}?function=${var.kong_api_key}"
}
```

The only error I get is something about an EOF.

**Comment by kevholditch** [comment]
Thanks for raising this issue. You cannot use the provider in this way as the kong admin uri currently is only meant to be the host. The rest of the kong url is appended to this. For example when querying APIs it’ll take this address and add the rest of the path to it. So for apis you would have https://localhost:8001?function=apikey/apis which isn’t valid.

I think the best way to solve this would be to allow configuration of a custom header that is passed with every request. You could then use that to pass your api key through. Would that work for you?

**Comment by mindflash-ops** [comment]
Adding the ability to access it via header would work fine, I'm not really picky about it.

**Comment by kevholditch** [comment]
Currently working on this but its a little more involved than first thought, should have something soon though
