### ISSUE TITLE
Provider doesn't work inside terraform docker image

### ISSUE THREAD

**Issue by tecnobrat** [kevholditch/terraform-provider-kong#25]
Hi Kev,

Looks like the released binaries do not work within the released terraform docker images.  It appears to be because the terraform docker images are run on alpine.

### Expected Behavior
The provider should work on the official terraform docker image

### Actual Behavior
Provider errors with `terraform-provider-kong_v1.2.0: not found`

### Steps to Reproduce
```
$ docker run -it -v "$(pwd):/providers" --entrypoint="/providers/terraform-provider-kong_v1.2.0" hashicorp/terraform
standard_init_linux.go:190: exec user process caused "no such file or directory"
```

You can see it executes on other non-alpine distros:

```
$ docker run -it -v "$(pwd):/providers" --entrypoint="/providers/terraform-provider-kong_v1.2.0" ubuntu

This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically
```

**Comment by tecnobrat** [comment]
Doing some research .. I found this:

https://github.com/Eneco/landscaper/issues/71

looks like you use goreleaser .. so I think adding this to make it statically linked will fix it?

```
env:
   - CGO_ENABLED=0
```

**Comment by tecnobrat** [comment]
I have created #26 and tested that a statically linked binary works under the default terraform docker image.

**Comment by kevholditch** [comment]
@tecnobrat thanks so much for this excellent contribution
