### ISSUE TITLE
JWT Resource

### ISSUE THREAD

**Issue by charles-d-burton** [kevholditch/terraform-provider-kong#3]
Looking at the  current state, I don't see a way to have this provider instruct Kong to create a JWT token for a consumer.  I think it would be very useful(at least in my use case) to have a resource that can create a JWT token for a consumer.  I was thinking it would look something like this:
```hcl
resource "kong_consumer_jwt" "consumer_token" {
  consumer_id = "${kong_consumer.consumer.id}"
}
```

Then have the outputs be each of the fields of the returned message.  

EDIT:  I'm basing this off the docs here:
https://getkong.org/plugins/jwt/#create-a-jwt-credential

**Comment by kevholditch** [comment]
@charles-d-burton I think you do not want to create a JWT token for a consumer but are you rather asking how you can instruct kong to use jwt for a certain consumer through terraform?  In effect how to do you call:
`curl -X POST http://kong:8001/consumers/{consumer}/jwt` ?

At the moment you are correct that is not able to do this.  The resource would require the following properties:
```
{
    "consumer_id": "7bce93e1-0a90-489c-c887-d385545f8f4b",
    "created_at": 1442426001000,
    "id": "bcbfb45d-e391-42bf-c2ed-94e32946753a",
    "key": "a36c3049b36249a3c9f8891cb127243c",
    "secret": "e71829c351aa4242c2719cbfbe671c09"
}
```
And is quite specific to the `jwt` plugin.  In effect we need a way to be able to configure a plugin for a consumer so perhaps a generic resource to do this that could be used with any plugin would be a better fit then it would cover all cases.  Do you want to have a go at a PR for this?

**Comment by charles-d-burton** [comment]
Sure, I was planning on coding something up.  I can also throw in creating groups as well so you can assign consumers to groups and bind them to APIs.

**Comment by charles-d-burton** [comment]
Looking through the docs it looks to me like there is a lot of variation in configuration options for plugins.  Some of them return values, some do not, other accept arguments, but some don't.  I'm curious if you think it would be better to isolate the configuration into a resource per plugin.  For instance, like this:
```hcl
resource "kong_plugin" "jwt" {
name = "jwt"
api_id = "${kong_api.api.id}"
}

resource "kong_plugin_jwt" {
consumer_id = "${kong_consumer.consumer.id}"
}
```

I like the idea of making it more generic, but I'm not sure how to handle the outputs mostly.  Each plugin config has outputs that vary based on the plugin.  For instance, here you define the outputs
```go
func resourceKongPluginRead(d *schema.ResourceData, meta interface{}) error {

	plugin, err := meta.(*gokong.KongAdminClient).Plugins().GetById(d.Id())

	if err != nil {
		return fmt.Errorf("could not find kong plugin: %v", err)
	}

	d.Set("name", plugin.Name)

	return nil
}
```
But in this case the outputs would differ depending on what kind of plugin you're configuring.  Meaning that the output mappings in the *schmea.ResourceData would be different.  This seems kind of messy and diverged from convention.

**Comment by kevholditch** [comment]
@charles-d-burton I've worked out how we can do it.  I've [pushed the work last night](https://github.com/kevholditch/gokong/commit/f1eb947e4e508e2cc920cedbe7f7c2eb246f7b5f) to support it in the `gokong` client which is what powers this provider.  From here I think we would have a resource that takes the plugin name, consumer id and configuration json

for example:
```hcl
resource "kong_consumer_plugin_config" {
    "consumer_id": "1234"
    "plugin_name": "jwt"
    "config_json": <<EOT
	{
    "consumer_id": "7bce93e1-0a90-489c-c887-d385545f8f4b",
    "created_at": 1442426001000,
    "id": "bcbfb45d-e391-42bf-c2ed-94e32946753a",
    "key": "a36c3049b36249a3c9f8891cb127243c",
    "secret": "e71829c351aa4242c2719cbfbe671c09"
}
EOT
}
```

That would then map onto the new endpoints in `gokong` to `CreatePluginConfig`, `GetPluginConfig` and `DeletePluginConfig` on the `Consumers` api.  The json payload we took would be passed straight though and stored in terraform state as is.  This way this resource can be used with any plugin and isn't just tied to the `jwt` plugin.  For example the `key-auth` plugin also gets configured.

**Comment by charles-d-burton** [comment]
I have a working plugin ready, just have to write the tests for it and I'll have it up for PR soonish.

**Comment by kevholditch** [comment]
@charles-d-burton  thanks for your contributions so far to this look really good.  I did an implementation of the plugin config too, its on a branch: https://github.com/kevholditch/terraform-provider-kong/tree/consumer-plugin-config, be good to get your thoughts?

**Comment by charles-d-burton** [comment]
I pulled that code down and made a bunch of edits.  Here's a summary of what I was thinking:
* I removed the necessity of passing in a config, a lot of endpoints don't necessarily accept a JSON body and will instead autogenerate their config when you make a call against it.
* I also added an update function, this basically deletes the old plugin config and pushes in the new one.
* I removed the validation piece of the json config, that could probably be added back in but I wasn't sure how necessary it was if the config isn't mandatory.
* I also modified the id generator, Kong generates nice random ids so I wasn't sure why other fields needed to be added.

https://github.com/charles-d-burton/terraform-provider-kong/tree/consumer-plugin-config

**Comment by kevholditch** [comment]
Merged and released as version `v0.10.0`

**Comment by charles-d-burton** [comment]
Hey thanks, I know the tests weren't passing that's why I didn't PR it.  Also wanted to make sure that what I was thinking wasn't out of whack.  Thanks for all your help on this!  If I run into more I'll definitely put some code together for it.

**Comment by kevholditch** [comment]
@charles-d-burton no worries thanks for using the provider and providing feedback.  Its great that people are getting use out of it.  Hope the new resource helps you out.  Thanks for all of your efforts so far!!
