### ISSUE TITLE
unmarshal error of type []*string

### ISSUE THREAD

**Issue by pepito987** [kevholditch/terraform-provider-kong#32]
I'm using kong v0.10.2, I'm using apis as Resource and I'm facing an unmarshal error.
It looks like that if a list field like `hosts` is empty this will set to an actual empty object {}
rather than empty list [].

After running PATCH on an apis resources:
`{ "hosts": [] }`

The GET will return:
`{ ..., "upstream_read_timeout": 60000, "upstream_send_timeout": 60000, "https_only": false, "hosts": {} }`
As you can see hosts is not an empty list but an empty object and terraform throw this during the import:
`could not find kong api: could not parse api get response, error: json: cannot unmarshal object into Go struct field Api.hosts of type []*string`

Also, I have the same error during a plan.

### Terraform Version
v0.11.0

### Expected Behavior
be able to import a resource with empty `hosts` list

### Actual Behavior
unmarshal error: `could not find kong api: could not parse api get response, error: json: cannot unmarshal object into Go struct field Api.hosts of type []*string`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. run PATCH to an api resources with body `{ "hosts": [] }`
2. run import of the api: `terraform import  module.proxy.kong_api.test-service e9da8a938-355b-4c69-ab26-2f507c688d02

**Comment by kevholditch** [comment]
which version of the terraform provider are you using as I cannot reproduce this

**Comment by pepito987** [comment]
I'm using `terraform-provider-kong_v1.5.0`

**Comment by kevholditch** [comment]
ok I can reproduce this now.  I tried to reproduce it directly in terraform by creating a resource with no hosts but kong seems to handle that ok.  It seems to be when you patch with an empty hosts array that you see this.  Will need to make a fix in `gokong` to handle this and pull that through into the terraform provider

**Comment by pepito987** [comment]
Thanks @kevholditch much appreciated. Is really weird for me that Kong marshal an empty list as empty object in the first place.

**Comment by kevholditch** [comment]
@pepito987 it looks like if you use the terraform provider for everything then you are fine.  Looks like a bug in kong that is caused by sending the payload `{"hosts":[]}`

**Comment by pepito987** [comment]
Well the issue in my case is that I'm importing existing resources which were managed manually via the web interface. 
Also, you have the same issue during a plan. If you set host to empty after creating the api, you won't be able to run a plan, because you will receive the same error.
Is it possible to abstract the base model to work with Objects and do the casting later checking the type first? In that case if empty object then empty list.

**Comment by kevholditch** [comment]
yeah but both of these issues are when you manually interface with the kong api yourself setting the hosts to an empty array outside of using terraform.  I think I know how I can fix this

**Comment by pepito987** [comment]
I would be surprised if the following scenario would work atm:
1) create api with hosts = ["example.com"] using terraform
2) update api to host = [] using terraform 
3) run a terraform plan
I would expect the same error here
