### ISSUE TITLE
Setting path from non-empty to an empty string broken

### ISSUE THREAD

**Issue by mlehner616** [kevholditch/terraform-provider-kong#40]
Hello,

When applying a change to a service path that contains a valid path to an empty string, terraform reports success but doesn't actually apply the change.

Example:
A service has a path set to /corp. As I apply the configuration that changes `/corp` to `""`, terraform reports the change was successfully applied but it actually was not.

```
Terraform will perform the following actions:

  ~ kong_service.service
      path: "/corp" => ""

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

kong_service.service: Modifying... (ID: 301f1020-6fa2-425f-b883-a77d47fbb892)
  path: "/corp" => ""
kong_service.service: Modifications complete after 0s (ID: 301f1020-6fa2-425f-b883-a77d47fbb892)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

Terraform version: 0.11.8
Kong 0.14.1
Affected Resources(s)
- kong_service (confirmed)
- kong_route (possibly)

EDIT: this may actually be a bug with kong

**Comment by kevholditch** [comment]
Is this still an issue?  I think this should be resolved now.
