### ISSUE TITLE
plugin works unstable via loop-back route and api-key auth

### ISSUE THREAD

**Issue by kapralVV** [kevholditch/terraform-provider-kong#46]
Hi @kevholditch ,

### Terraform Version
terraform -v
Terraform v0.11.8

### Affected Resource(s)
kong_service

### Expected Behavior
It should create a service only once. 

### Actual Behavior
`terrafrom plan` shows randomly  that kongs service has to be created even it's done.
It may affect any service or may not, occurs randomly. 

### Steps to Reproduce
1. configure loop-back route to kong admin api with api-key 
2. `terraform plan`  -> works good
3. `terrafrom apply` -> works good 
4. `terrafrom plan` multiple times -> will show that a service has to be created even it's created on step 3. 
5. some `terraform plan` execution may show correct status. 

Let me know if some additional information is required. Thanks

**Comment by kevholditch** [comment]
@kapralVV do you want to have a go at fixing?

**Comment by kapralVV** [comment]
@kevholditch  
sure. Let me know if something required to be provided : debug-log or so.

**Comment by kapralVV** [comment]
@kevholditch 
I found It occurs with the direct connection to kong-admin not only with loopBack but more rare 
kong version 0.13

**Comment by aint** [comment]
Hi there, 
I'm experiencing the same issue even without a loopback. 
Is﻿ there any chance to fix it? 

Anyway, thanks for the great plugin.

**Comment by kapralVV** [comment]
Root of cause is here 
https://github.com/Kong/kong/issues/3440
I've applied commit below and it works for me 
https://github.com/Kong/kong/pull/3423
Thanks. Closing the issue
