### ISSUE TITLE
Cannot create HTTP/HTTPS route using provider ver. 4.5

### ISSUE THREAD

**Issue by mirkoszy** [kevholditch/terraform-provider-kong#76]
I use Kong EE v0.34

I use https://github.com/kevholditch/terraform-provider-kong/releases/tag/v4.5.0.

I tried to create HTTP/HTTPS route as in readme:

```
resource "kong_route" "route" {
    name            = "MyRoute"
	protocols 	    = [ "http", "https" ]
	methods 	    = [ "GET", "POST" ]
	hosts 		    = [ "example2.com" ]
	paths 		    = [ "/test" ]
	strip_path 	    = false
	preserve_host 	= true
	regex_priority 	= 1
	service_id 	    = "${kong_service.service.id}"
}
```

I get the following error:

> error: could not register the route, error: {"fields":{"destinations":"unknown field","name":"unknown field","snis":"unknown field","sources":"unknown field"},"name":"schema violation","code":2,"message":"4 schema violations (destinations: unknown field; name: unknown field; snis: unknown field; sources: unknown field)"}

It means that parameters for TCP route are sent. 

https://github.com/kevholditch/terraform-provider-kong/issues/59 here was the same problem but issue is closed.

EDIT. 
I used provider version 1.9.2 and it works. Does admin api in enterprise edition is far behind the community edition?

**Comment by kevholditch** [comment]
@mirkoszy unfortunately I don't have access to enterprise kong so I don't know the exact state of play, however I believe that it is based upon kong pre `1.0.0` which means that the latest terraform provider will not work with it.  Until enterprise gets upgraded you will have to stick with the pre `1.0.0` versions of the provider I'm afraid like `1.9.2`
