### ISSUE TITLE
Update README.md to reflect the removal of "config" from resource_kong_consumer_plugin_config

### ISSUE THREAD

**Issue by bneutra** [kevholditch/terraform-provider-kong#79]
First of all, thanks for the provider, once I get to know the ropes hopefully I can contribute some PR's. I believe the README.md around kong/resource_kong_consumer_plugin_config.go is out of date. For me configuring a consumer with the acl plugin (tf 0.11.14, kong 1.1) using config_json with the "acl" plugin works just fine. The README.md says you must use "config" but that doesn't work, which I think you can see why, it was removed here:

https://github.com/kevholditch/terraform-provider-kong/commit/e89326af1dd4eeabfcf0be7bcd1f91df4b2222ee#diff-6c4ac886194357f39f8e55ebddfdc86b

e.g. this worked fine

resource "kong_consumer_plugin_config" "consumer_acl" {
	consumer_id = "${kong_consumer.test.id}"
        plugin_name = "acls"
	config_json = <<EOT
	{
           "group": "group1"
	}
EOT
}

while what is indicated in the README.md does not
Error: kong_consumer_plugin_config.consumer_acl: : invalid or unknown key: config

**Comment by bneutra** [comment]
I opened this in part to just confirm that I'm not missing some context (i.e. it's ok for me to use the consumer config that I am using)

**Comment by kevholditch** [comment]
@bneutra thanks for raising this.  You are correct that it is a mistake in the readme.  Feel free to do a PR to fix this

**Comment by bneutra** [comment]
I have opened https://github.com/kevholditch/terraform-provider-kong/pull/84
