### ISSUE TITLE
Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

### ISSUE THREAD

**Issue by Yamilquery** [kevholditch/terraform-provider-kong#83]
Hi there, I have an issue when I upgrade my terraform.

I'm getting the following error:

`Failed to instantiate provider "kong" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]`

How can I solve it...

Thank you!

**Comment by kevholditch** [comment]
provider doesn't support `v0.12` of terraform yet, this is coming soon, see #82
