### ISSUE TITLE
kong workspace is not supported

### ISSUE THREAD

**Issue by jassmakhija** [kevholditch/terraform-provider-kong#85]
Hi,

I need to create kong workspace using this plugin with terraform but it seems kong workspace is not supported

**Comment by kevholditch** [comment]
hi @jassmakhija, can you please provide more information so that we can try and reproduce the issue

**Comment by jassmakhija** [comment]
Hi Kevin,

Thanks for reaching me out.

We are using kong enterprise version .34 and hence Kong plugin version 1.9.1

Kong have workspaces concept now and I want to create a new workspace using terraform and your plugin. More details here https://docs.konghq.com/enterprise/0.33-x/workspaces/examples/

I couldnt find the corresponding resource name in terraform provider plugin for creating a workspace. 

Let me know if you need more information.

**Comment by jassmakhija** [comment]
Hi Kevin,

Is this something looks a valid issue to you? Appreciate if you could confirm if you are working on this?

**Comment by kevholditch** [comment]
hi @jassmakhija, unfortunately the provider only supports limited functionality for Kong Enterprise as I do not pay for Kong Enterprise so have no way to develop with it.  All of the features that are common between Kong standard and enterprise should work fine but additional features may not work.

**Comment by jassmakhija** [comment]
Thanks for the response @kevholditch.
