### ISSUE TITLE
Add https_redirect_status_code for Route object 

### ISSUE THREAD

**Issue by nghnam** [kevholditch/terraform-provider-kong#98]
Kong supports `http_redirect_status_code` from v1.2 to support redirect HTTP to HTTPS.
Ref: https://docs.konghq.com/1.2.x/admin-api/#route-object

The feature request is:
Add `http_redirect_status_code` in body of request when creating Route object

**Comment by kevholditch** [comment]
Hi, this has been implemented in the latest version of the provider `v6.1.3`
